<?php

return [
    "ABW" => [
        "id" => "ABW",
        "iso" => "AW",
        "name" => "ARUBA",
        "country" => "Aruba",
        "numcode" => "533",
        "flag" => "Aruba-Flag.png",
    ],
    "AFG" => [
        "id" => "AFG",
        "iso" => "AF",
        "name" => "AFGHANISTAN",
        "country" => "Afghanistan",
        "numcode" => "4",
        "flag" => "Afghanistan-Flag.png",
    ],
    "AGO" => [
        "id" => "AGO",
        "iso" => "AO",
        "name" => "ANGOLA",
        "country" => "Angola",
        "numcode" => "24",
        "flag" => "Angola-Flag.png",
    ],
    "AIA" => [
        "id" => "AIA",
        "iso" => "AI",
        "name" => "ANGUILLA",
        "country" => "Anguilla",
        "numcode" => "660",
        "flag" => "Anguilla-Flag.png",
    ],
    "ALB" => [
        "id" => "ALB",
        "iso" => "AL",
        "name" => "ALBANIA",
        "country" => "Albania",
        "numcode" => "8",
        "flag" => "Albania-Flag.png",
    ],
    "AND" => [
        "id" => "AND",
        "iso" => "AD",
        "name" => "ANDORRA",
        "country" => "Andorra",
        "numcode" => "20",
        "flag" => "Andorra-Flag.png",
    ],
    "ANT" => [
        "id" => "ANT",
        "iso" => "AN",
        "name" => "NETHERLANDS ANTILLES",
        "country" => "Netherlands Antilles",
        "numcode" => "530",
        "flag" => "Netherlands-Antilles-Flag.png",
    ],
    "AQ" => [
        "id" => "AQ",
        "iso" => "AQ",
        "name" => "ANTARCTICA",
        "country" => "Antarctica",
        "numcode" => "0",
        "flag" => "Antarctica-Flag.png",
    ],
    "ARE" => [
        "id" => "ARE",
        "iso" => "AE",
        "name" => "UNITED ARAB EMIRATES",
        "country" => "United Arab Emirates",
        "numcode" => "784",
        "flag" => "United-Arab-Emirates-Flag.png",
    ],
    "ARG" => [
        "id" => "ARG",
        "iso" => "AR",
        "name" => "ARGENTINA",
        "country" => "Argentina",
        "numcode" => "32",
        "flag" => "Argentina-Flag.png",
    ],
    "ARM" => [
        "id" => "ARM",
        "iso" => "AM",
        "name" => "ARMENIA",
        "country" => "Armenia",
        "numcode" => "51",
        "flag" => "Armenia-Flag.png",
    ],
    "ASM" => [
        "id" => "ASM",
        "iso" => "AS",
        "name" => "AMERICAN SAMOA",
        "country" => "American Samoa",
        "numcode" => "16",
        "flag" => "American-Samoa-Flag.png",
    ],
    "ATG" => [
        "id" => "ATG",
        "iso" => "AG",
        "name" => "ANTIGUA AND BARBUDA",
        "country" => "Antigua and Barbuda",
        "numcode" => "28",
        "flag" => "Antigua-and-Barbuda-Flag.png",
    ],
    "AUS" => [
        "id" => "AUS",
        "iso" => "AU",
        "name" => "AUSTRALIA",
        "country" => "Australia",
        "numcode" => "36",
        "flag" => "Australia-Flag.png",
    ],
    "AUT" => [
        "id" => "AUT",
        "iso" => "AT",
        "name" => "AUSTRIA",
        "country" => "Austria",
        "numcode" => "40",
        "flag" => "Austria-Flag.png",
    ],
    "AZE" => [
        "id" => "AZE",
        "iso" => "AZ",
        "name" => "AZERBAIJAN",
        "country" => "Azerbaijan",
        "numcode" => "31",
        "flag" => "Azerbaijan-Flag.png",
    ],
    "BDI" => [
        "id" => "BDI",
        "iso" => "BI",
        "name" => "BURUNDI",
        "country" => "Burundi",
        "numcode" => "108",
        "flag" => "Burundi-Flag.png",
    ],
    "BEL" => [
        "id" => "BEL",
        "iso" => "BE",
        "name" => "BELGIUM",
        "country" => "Belgium",
        "numcode" => "56",
        "flag" => "Belgium-Flag.png",
    ],
    "BEN" => [
        "id" => "BEN",
        "iso" => "BJ",
        "name" => "BENIN",
        "country" => "Benin",
        "numcode" => "204",
        "flag" => "Benin-Flag.png",
    ],
    "BFA" => [
        "id" => "BFA",
        "iso" => "BF",
        "name" => "BURKINA FASO",
        "country" => "Burkina Faso",
        "numcode" => "854",
        "flag" => "Burkina-Faso-Flag.png",
    ],
    "BGD" => [
        "id" => "BGD",
        "iso" => "BD",
        "name" => "BANGLADESH",
        "country" => "Bangladesh",
        "numcode" => "50",
        "flag" => "Bangladesh-Flag.png",
    ],
    "BGR" => [
        "id" => "BGR",
        "iso" => "BG",
        "name" => "BULGARIA",
        "country" => "Bulgaria",
        "numcode" => "100",
        "flag" => "Bulgaria-Flag.png",
    ],
    "BHR" => [
        "id" => "BHR",
        "iso" => "BH",
        "name" => "BAHRAIN",
        "country" => "Bahrain",
        "numcode" => "48",
        "flag" => "Bahrain-Flag.png",
    ],
    "BHS" => [
        "id" => "BHS",
        "iso" => "BS",
        "name" => "BAHAMAS",
        "country" => "Bahamas",
        "numcode" => "44",
        "flag" => "Bahamas-Flag.png",
    ],
    "BIH" => [
        "id" => "BIH",
        "iso" => "BA",
        "name" => "BOSNIA AND HERZEGOVINA",
        "country" => "Bosnia and Herzegovina",
        "numcode" => "70",
        "flag" => "Bosnia-and-Herzegovina-Flag.png",
    ],
    "BLR" => [
        "id" => "BLR",
        "iso" => "BY",
        "name" => "BELARUS",
        "country" => "Belarus",
        "numcode" => "112",
        "flag" => "Belarus-Flag.png",
    ],
    "BLZ" => [
        "id" => "BLZ",
        "iso" => "BZ",
        "name" => "BELIZE",
        "country" => "Belize",
        "numcode" => "84",
        "flag" => "Belize-Flag.png",
    ],
    "BMU" => [
        "id" => "BMU",
        "iso" => "BM",
        "name" => "BERMUDA",
        "country" => "Bermuda",
        "numcode" => "60",
        "flag" => "Bermuda-Flag.png",
    ],
    "BOL" => [
        "id" => "BOL",
        "iso" => "BO",
        "name" => "BOLIVIA",
        "country" => "Bolivia",
        "numcode" => "68",
        "flag" => "Bolivia-Flag.png",
    ],
    "BRA" => [
        "id" => "BRA",
        "iso" => "BR",
        "name" => "BRAZIL",
        "country" => "Brazil",
        "numcode" => "76",
        "flag" => "Brazil-Flag.png",
    ],
    "BRB" => [
        "id" => "BRB",
        "iso" => "BB",
        "name" => "BARBADOS",
        "country" => "Barbados",
        "numcode" => "52",
        "flag" => "Barbados-Flag.png",
    ],
    "BRN" => [
        "id" => "BRN",
        "iso" => "BN",
        "name" => "BRUNEI DARUSSALAM",
        "country" => "Brunei Darussalam",
        "numcode" => "96",
        "flag" => "Brunei-Flag.png",
    ],
    "BTN" => [
        "id" => "BTN",
        "iso" => "BT",
        "name" => "BHUTAN",
        "country" => "Bhutan",
        "numcode" => "64",
        "flag" => "Bhutan-Flag.png",
    ],
    "BWA" => [
        "id" => "BWA",
        "iso" => "BW",
        "name" => "BOTSWANA",
        "country" => "Botswana",
        "numcode" => "72",
        "flag" => "Botswana-Flag.png",
    ],
    "CAF" => [
        "id" => "CAF",
        "iso" => "CF",
        "name" => "CENTRAL AFRICAN REPUBLIC",
        "country" => "Central African Republic",
        "numcode" => "140",
        "flag" => "Central-African-Republic-Flag.png",
    ],
    "CAN" => [
        "id" => "CAN",
        "iso" => "CA",
        "name" => "CANADA",
        "country" => "Canada",
        "numcode" => "124",
        "flag" => "Canada-Flag.png",
    ],
    "CHE" => [
        "id" => "CHE",
        "iso" => "CH",
        "name" => "SWITZERLAND",
        "country" => "Switzerland",
        "numcode" => "756",
        "flag" => "Switzerland-Flag.png",
    ],
    "CHL" => [
        "id" => "CHL",
        "iso" => "CL",
        "name" => "CHILE",
        "country" => "Chile",
        "numcode" => "152",
        "flag" => "Chile-Flag.png",
    ],
    "CHN" => [
        "id" => "CHN",
        "iso" => "CN",
        "name" => "CHINA",
        "country" => "China",
        "numcode" => "156",
        "flag" => "China-Flag.png",
    ],
    "CIV" => [
        "id" => "CIV",
        "iso" => "CI",
        "name" => "COTE D'IVOIRE",
        "country" => "Cote D'Ivoire",
        "numcode" => "384",
        "flag" => "Cote-DIvoire-Flag.png",
    ],
    "CMR" => [
        "id" => "CMR",
        "iso" => "CM",
        "name" => "CAMEROON",
        "country" => "Cameroon",
        "numcode" => "120",
        "flag" => "Cameroon-Flag.png",
    ],
    "COD" => [
        "id" => "COD",
        "iso" => "CD",
        "name" => "CONGO, THE DEMOCRATIC REPUBLIC OF THE",
        "country" => "Congo, the Democratic Republic of the",
        "numcode" => "180",
        "flag" => "Congo-Kinshasa-Flag.png",
    ],
    "COG" => [
        "id" => "COG",
        "iso" => "CG",
        "name" => "CONGO",
        "country" => "Congo",
        "numcode" => "178",
        "flag" => "Congo-Brazzaville-Flag.png",
    ],
    "COK" => [
        "id" => "COK",
        "iso" => "CK",
        "name" => "COOK ISLANDS",
        "country" => "Cook Islands",
        "numcode" => "184",
        "flag" => "Cook-Islands-Flag.png",
    ],
    "COL" => [
        "id" => "COL",
        "iso" => "CO",
        "name" => "COLOMBIA",
        "country" => "Colombia",
        "numcode" => "170",
        "flag" => "Colombia-Flag.png",
    ],
    "COM" => [
        "id" => "COM",
        "iso" => "KM",
        "name" => "COMOROS",
        "country" => "Comoros",
        "numcode" => "174",
        "flag" => "Comoros-Flag.png",
    ],
    "CPV" => [
        "id" => "CPV",
        "iso" => "CV",
        "name" => "CAPE VERDE",
        "country" => "Cape Verde",
        "numcode" => "132",
        "flag" => "Cape-Verde-Flag.png",
    ],
    "CRI" => [
        "id" => "CRI",
        "iso" => "CR",
        "name" => "COSTA RICA",
        "country" => "Costa Rica",
        "numcode" => "188",
        "flag" => "Costa-Rica-Flag.png",
    ],
    "CS" => [
        "id" => "CS",
        "iso" => "CS",
        "name" => "SERBIA AND MONTENEGRO",
        "country" => "Serbia and Montenegro",
        "numcode" => "0",
        "flag" => "Serbia-Flag.png",
    ],
    "CUB" => [
        "id" => "CUB",
        "iso" => "CU",
        "name" => "CUBA",
        "country" => "Cuba",
        "numcode" => "192",
        "flag" => "Cuba-Flag.png",
    ],
    "CYM" => [
        "id" => "CYM",
        "iso" => "KY",
        "name" => "CAYMAN ISLANDS",
        "country" => "Cayman Islands",
        "numcode" => "136",
        "flag" => "Cayman-Islands-Flag.png",
    ],
    "CYP" => [
        "id" => "CYP",
        "iso" => "CY",
        "name" => "CYPRUS",
        "country" => "Cyprus",
        "numcode" => "196",
        "flag" => "Cyprus-Flag.png",
    ],
    "CZE" => [
        "id" => "CZE",
        "iso" => "CZ",
        "name" => "CZECH REPUBLIC",
        "country" => "Czech Republic",
        "numcode" => "203",
        "flag" => "Czech-Republic-Flag.png",
    ],
    "DEU" => [
        "id" => "DEU",
        "iso" => "DE",
        "name" => "GERMANY",
        "country" => "Germany",
        "numcode" => "276",
        "flag" => "Germany-Flag.png",
    ],
    "DJI" => [
        "id" => "DJI",
        "iso" => "DJ",
        "name" => "DJIBOUTI",
        "country" => "Djibouti",
        "numcode" => "262",
        "flag" => "Djibouti-Flag.png",
    ],
    "DMA" => [
        "id" => "DMA",
        "iso" => "DM",
        "name" => "DOMINICA",
        "country" => "Dominica",
        "numcode" => "212",
        "flag" => "Dominica-Flag.png",
    ],
    "DNK" => [
        "id" => "DNK",
        "iso" => "DK",
        "name" => "DENMARK",
        "country" => "Denmark",
        "numcode" => "208",
        "flag" => "Denmark-Flag.png",
    ],
    "DOM" => [
        "id" => "DOM",
        "iso" => "DO",
        "name" => "DOMINICAN REPUBLIC",
        "country" => "Dominican Republic",
        "numcode" => "214",
        "flag" => "Dominican-Republic-Flag.png",
    ],
    "DZA" => [
        "id" => "DZA",
        "iso" => "DZ",
        "name" => "ALGERIA",
        "country" => "Algeria",
        "numcode" => "12",
        "flag" => "Algeria-Flag.png",
    ],
    "ECU" => [
        "id" => "ECU",
        "iso" => "EC",
        "name" => "ECUADOR",
        "country" => "Ecuador",
        "numcode" => "218",
        "flag" => "Ecuador-Flag.png",
    ],
    "EGY" => [
        "id" => "EGY",
        "iso" => "EG",
        "name" => "EGYPT",
        "country" => "Egypt",
        "numcode" => "818",
        "flag" => "Egypt-Flag.png",
    ],
    "ERI" => [
        "id" => "ERI",
        "iso" => "ER",
        "name" => "ERITREA",
        "country" => "Eritrea",
        "numcode" => "232",
        "flag" => "Eritrea-Flag.png",
    ],
    "ESH" => [
        "id" => "ESH",
        "iso" => "EH",
        "name" => "WESTERN SAHARA",
        "country" => "Western Sahara",
        "numcode" => "732",
        "flag" => "Western-Sahara-Flag.png",
    ],
    "ESP" => [
        "id" => "ESP",
        "iso" => "ES",
        "name" => "SPAIN",
        "country" => "Spain",
        "numcode" => "724",
        "flag" => "Spain-Flag.png",
    ],
    "EST" => [
        "id" => "EST",
        "iso" => "EE",
        "name" => "ESTONIA",
        "country" => "Estonia",
        "numcode" => "233",
        "flag" => "Estonia-Flag.png",
    ],
    "ETH" => [
        "id" => "EST",
        "iso" => "ET",
        "name" => "ETHIOPIA",
        "country" => "Ethiopia",
        "numcode" => "231",
        "flag" => "Ethiopia-Flag.png",
    ],
    "FIN" => [
        "id" => "FIN",
        "iso" => "FI",
        "name" => "FINLAND",
        "country" => "Finland",
        "numcode" => "246",
        "flag" => "Finland-Flag.png",
    ],
    "FJI" => [
        "id" => "FJI",
        "iso" => "FJ",
        "name" => "FIJI",
        "country" => "Fiji",
        "numcode" => "242",
        "flag" => "Fiji-Flag.png",
    ],
    "FLK" => [
        "id" => "FLK",
        "iso" => "FK",
        "name" => "FALKLAND ISLANDS (MALVINAS]",
        "country" => "Falkland Islands (Malvinas]",
        "numcode" => "238",
        "flag" => "United-Kingdom-Flag.png",
    ],
    "FRA" => [
        "id" => "FRA",
        "iso" => "FR",
        "name" => "FRANCE",
        "country" => "France",
        "numcode" => "250",
        "flag" => "France-Flag.png",
    ],
    "FRO" => [
        "id" => "FRO",
        "iso" => "FO",
        "name" => "FAROE ISLANDS",
        "country" => "Faroe Islands",
        "numcode" => "234",
        "flag" => "Faroes-Flag.png",
    ],
    "FSM" => [
        "id" => "FSM",
        "iso" => "FM",
        "name" => "MICRONESIA, FEDERATED STATES OF",
        "country" => "Micronesia, Federated States of",
        "numcode" => "583",
        "flag" => "Micronesia-Flag.png",
    ],
    "GAB" => [
        "id" => "GAB",
        "iso" => "GA",
        "name" => "GABON",
        "country" => "Gabon",
        "numcode" => "266",
        "flag" => "Gabon-Flag.png",
    ],
    "GBR" => [
        "id" => "GBR",
        "iso" => "GB",
        "name" => "UNITED KINGDOM",
        "country" => "United Kingdom",
        "numcode" => "826",
        "flag" => "United-Kingdom-Flag.png",
    ],
    "GEO" => [
        "id" => "GEO",
        "iso" => "GE",
        "name" => "GEORGIA",
        "country" => "Georgia",
        "numcode" => "268",
        "flag" => "Georgia-Flag.png",
    ],
    "GHA" => [
        "id" => "GHA",
        "iso" => "GH",
        "name" => "GHANA",
        "country" => "Ghana",
        "numcode" => "288",
        "flag" => "Ghana-Flag.png",
    ],
    "GIB" => [
        "id" => "GIB",
        "iso" => "GI",
        "name" => "GIBRALTAR",
        "country" => "Gibraltar",
        "numcode" => "292",
        "flag" => "Gibraltar-Flag.png",
    ],
    "GIN" => [
        "id" => "GIN",
        "iso" => "GN",
        "name" => "GUINEA",
        "country" => "Guinea",
        "numcode" => "324",
        "flag" => "Guinea-Flag.png",
    ],
    "GLP" => [
        "id" => "GLP",
        "iso" => "GP",
        "name" => "GUADELOUPE",
        "country" => "Guadeloupe",
        "numcode" => "312",
        "flag" => "France-Flag.png",
    ],
    "GMB" => [
        "id" => "GMB",
        "iso" => "GM",
        "name" => "GAMBIA",
        "country" => "Gambia",
        "numcode" => "270",
        "flag" => "Gambia-Flag.png",
    ],
    "GNB" => [
        "id" => "GNB",
        "iso" => "GW",
        "name" => "GUINEA-BISSAU",
        "country" => "Guinea-Bissau",
        "numcode" => "624",
        "flag" => "Guinea-Bissau-Flag.png",
    ],
    "GNQ" => [
        "id" => "GNQ",
        "iso" => "GQ",
        "name" => "EQUATORIAL GUINEA",
        "country" => "Equatorial Guinea",
        "numcode" => "226",
        "flag" => "Equatorial-Guinea-Flag.png",
    ],
    "GRC" => [
        "id" => "GRC",
        "iso" => "GR",
        "name" => "GREECE",
        "country" => "Greece",
        "numcode" => "300",
        "flag" => "Greece-Flag.png",
    ],
    "GRD" => [
        "id" => "GRD",
        "iso" => "GD",
        "name" => "GRENADA",
        "country" => "Grenada",
        "numcode" => "308",
        "flag" => "Grenada-Flag.png",
    ],
    "GRL" => [
        "id" => "GRL",
        "iso" => "GL",
        "name" => "GREENLAND",
        "country" => "Greenland",
        "numcode" => "304",
        "flag" => "Denmark-Flag.png",
    ],
    "GS" => [
        "id" => "GS",
        "iso" => "GS",
        "name" => "SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS",
        "country" => "South Georgia and the South Sandwich Islands",
        "numcode" => "0",
        "flag" => "South-Korea-Flag.png",
    ],
    "GTM" => [
        "id" => "GTM",
        "iso" => "GT",
        "name" => "GUATEMALA",
        "country" => "Guatemala",
        "numcode" => "320",
        "flag" => "Guatemala-Flag.png",
    ],
    "GUF" => [
        "id" => "GUF",
        "iso" => "GF",
        "name" => "FRENCH GUIANA",
        "country" => "French Guiana",
        "numcode" => "254",
        "flag" => "France-Flag.png",
    ],
    "GUM" => [
        "id" => "GUM",
        "iso" => "GU",
        "name" => "GUAM",
        "country" => "Guam",
        "numcode" => "316",
        "flag" => "Guam-Flag.png",
    ],
    "GUY" => [
        "id" => "GUY",
        "iso" => "GY",
        "name" => "GUYANA",
        "country" => "Guyana",
        "numcode" => "328",
        "flag" => "Guyana-Flag.png",
    ],
    "HKG" => [
        "id" => "HKG",
        "iso" => "HK",
        "name" => "HONG KONG",
        "country" => "Hong Kong",
        "numcode" => "344",
        "flag" => "Hong-Kong-Flag.png",
    ],
    "HM" => [
        "id" => "HM",
        "iso" => "HM",
        "name" => "HEARD ISLAND AND MCDONALD ISLANDS",
        "country" => "Heard Island and Mcdonald Islands",
        "numcode" => "0",
        "flag" => "Australia-Flag.png",
    ],
    "HND" => [
        "id" => "HND",
        "iso" => "HN",
        "name" => "HONDURAS",
        "country" => "Honduras",
        "numcode" => "340",
        "flag" => "Honduras-Flag.png",
    ],
    "HRV" => [
        "id" => "HRV",
        "iso" => "HR",
        "name" => "CROATIA",
        "country" => "Croatia",
        "numcode" => "191",
        "flag" => "Croatia-Flag.png",
    ],
    "HTI" => [
        "id" => "HTI",
        "iso" => "HT",
        "name" => "HAITI",
        "country" => "Haiti",
        "numcode" => "332",
        "flag" => "Haiti-Flag.png",
    ],
    "HUN" => [
        "id" => "HUN",
        "iso" => "HU",
        "name" => "HUNGARY",
        "country" => "Hungary",
        "numcode" => "348",
        "flag" => "Hungary-Flag.png",
    ],
    "IDN" => [
        "id" => "IDN",
        "iso" => "ID",
        "name" => "INDONESIA",
        "country" => "Indonesia",
        "numcode" => "360",
        "flag" => "Indonezia-Flag.png",
    ],
    "IND" => [
        "id" => "IND",
        "iso" => "IN",
        "name" => "INDIA",
        "country" => "India",
        "numcode" => "356",
        "flag" => "India-Flag.png",
    ],
    "IRL" => [
        "id" => "IRL",
        "iso" => "IE",
        "name" => "IRELAND",
        "country" => "Ireland",
        "numcode" => "372",
        "flag" => "Ireland-Flag.png",
    ],
    "IRN" => [
        "id" => "IRN",
        "iso" => "IR",
        "name" => "IRAN, ISLAMIC REPUBLIC OF",
        "country" => "Iran, Islamic Republic of",
        "numcode" => "364",
        "flag" => "Iran-Flag.png",
    ],
    "IRQ" => [
        "id" => "IRQ",
        "iso" => "IQ",
        "name" => "IRAQ",
        "country" => "Iraq",
        "numcode" => "368",
        "flag" => "Iraq-Flag.png",
    ],
    "ISL" => [
        "id" => "ISL",
        "iso" => "IS",
        "name" => "ICELAND",
        "country" => "Iceland",
        "numcode" => "352",
        "flag" => "Iceland-Flag.png",
    ],
    "ISR" => [
        "id" => "ISR",
        "iso" => "IL",
        "name" => "ISRAEL",
        "country" => "Israel",
        "numcode" => "376",
        "flag" => "Israel-Flag.png",
    ],
    "ITA" => [
        "id" => "ITA",
        "iso" => "IT",
        "name" => "ITALY",
        "country" => "Italy",
        "numcode" => "380",
        "flag" => "Italy-Flag.png",
    ],
    "JAM" => [
        "id" => "JAM",
        "iso" => "JM",
        "name" => "JAMAICA",
        "country" => "Jamaica",
        "numcode" => "388",
        "flag" => "Jamaica-Flag.png",
    ],
    "JOR" => [
        "id" => "JOR",
        "iso" => "JO",
        "name" => "JORDAN",
        "country" => "Jordan",
        "numcode" => "400",
        "flag" => "Jordan-Flag.png",
    ],
    "JPN" => [
        "id" => "JPN",
        "iso" => "JP",
        "name" => "JAPAN",
        "country" => "Japan",
        "numcode" => "392",
        "flag" => "Japan-Flag.png",
    ],
    "KAZ" => [
        "id" => "KAZ",
        "iso" => "KZ",
        "name" => "KAZAKHSTAN",
        "country" => "Kazakhstan",
        "numcode" => "398",
        "flag" => "Kazakhstan-Flag.png",
    ],
    "KEN" => [
        "id" => "KEN",
        "iso" => "KE",
        "name" => "KENYA",
        "country" => "Kenya",
        "numcode" => "404",
        "flag" => "Kenya-Flag.png",
    ],
    "KGZ" => [
        "id" => "KGZ",
        "iso" => "KG",
        "name" => "KYRGYZSTAN",
        "country" => "Kyrgyzstan",
        "numcode" => "417",
        "flag" => "Kyrgyzstan-Flag.png",
    ],
    "KHM" => [
        "id" => "KHM",
        "iso" => "KH",
        "name" => "CAMBODIA",
        "country" => "Cambodia",
        "numcode" => "116",
        "flag" => "Cambodia-Flag.png",
    ],
    "KIR" => [
        "id" => "KIR",
        "iso" => "KI",
        "name" => "KIRIBATI",
        "country" => "Kiribati",
        "numcode" => "296",
        "flag" => "Kiribati-Flag.png",
    ],
    "KNA" => [
        "id" => "KNA",
        "iso" => "KN",
        "name" => "SAINT KITTS AND NEVIS",
        "country" => "Saint Kitts and Nevis",
        "numcode" => "659",
        "flag" => "St-Kitts-and-Nevis-Flag.png",
    ],
    "KOR" => [
        "id" => "KOR",
        "iso" => "KR",
        "name" => "KOREA, REPUBLIC OF",
        "country" => "Korea, Republic of",
        "numcode" => "410",
        "flag" => "South-Korea-Flag.png",
    ],
    "KWT" => [
        "id" => "KWT",
        "iso" => "KW",
        "name" => "KUWAIT",
        "country" => "Kuwait",
        "numcode" => "414",
        "flag" => "Kuwait-Flag.png",
    ],
    "LAO" => [
        "id" => "LAO",
        "iso" => "LA",
        "name" => "LAO PEOPLE'S DEMOCRATIC REPUBLIC",
        "country" => "Lao People's Democratic Republic",
        "numcode" => "418",
        "flag" => "Laos-Flag.png",
    ],
    "LBN" => [
        "id" => "LBN",
        "iso" => "LB",
        "name" => "LEBANON",
        "country" => "Lebanon",
        "numcode" => "422",
        "flag" => "Lebanon-Flag.png",
    ],
    "LBR" => [
        "id" => "LBR",
        "iso" => "LR",
        "name" => "LIBERIA",
        "country" => "Liberia",
        "numcode" => "430",
        "flag" => "Liberia-Flag.png",
    ],
    "LBY" => [
        "id" => "LBY",
        "iso" => "LY",
        "name" => "LIBYAN ARAB JAMAHIRIYA",
        "country" => "Libyan Arab Jamahiriya",
        "numcode" => "434",
        "flag" => "Libya-Flag.png",
    ],
    "LCA" => [
        "id" => "LCA",
        "iso" => "LC",
        "name" => "SAINT LUCIA",
        "country" => "Saint Lucia",
        "numcode" => "662",
        "flag" => "Saint-Lucia-Flag.png",
    ],
    "LIE" => [
        "id" => "LIE",
        "iso" => "LI",
        "name" => "LIECHTENSTEIN",
        "country" => "Liechtenstein",
        "numcode" => "438",
        "flag" => "Liechtenshein-Flag.png",
    ],
    "LKA" => [
        "id" => "LKA",
        "iso" => "LK",
        "name" => "SRI LANKA",
        "country" => "Sri Lanka",
        "numcode" => "144",
        "flag" => "Sri-Lanka-Flag.png",
    ],
    "LSO" => [
        "id" => "LSO",
        "iso" => "LS",
        "name" => "LESOTHO",
        "country" => "Lesotho",
        "numcode" => "426",
        "flag" => "Lesotho-Flag.png",
    ],
    "LTU" => [
        "id" => "LTU",
        "iso" => "LT",
        "name" => "LITHUANIA",
        "country" => "Lithuania",
        "numcode" => "440",
        "flag" => "Lithuania-Flag.png",
    ],
    "LUX" => [
        "id" => "LUX",
        "iso" => "LU",
        "name" => "LUXEMBOURG",
        "country" => "Luxembourg",
        "numcode" => "442",
        "flag" => "Luxembourg-Flag.png",
    ],
    "LVA" => [
        "id" => "LVA",
        "iso" => "LV",
        "name" => "LATVIA",
        "country" => "Latvia",
        "numcode" => "428",
        "flag" => "Latvia-Flag.png",
    ],
    "MAC" => [
        "id" => "MAC",
        "iso" => "MO",
        "name" => "MACAO",
        "country" => "Macao",
        "numcode" => "446",
        "flag" => "Macau-Flag.png",
    ],
    "MAR" => [
        "id" => "MAR",
        "iso" => "MA",
        "name" => "MOROCCO",
        "country" => "Morocco",
        "numcode" => "504",
        "flag" => "Morocco-Flag.png",
    ],
    "MCO" => [
        "id" => "MCO",
        "iso" => "MC",
        "name" => "MONACO",
        "country" => "Monaco",
        "numcode" => "492",
        "flag" => "Monaco-Flag.png",
    ],
    "MDA" => [
        "id" => "MDA",
        "iso" => "MD",
        "name" => "MOLDOVA, REPUBLIC OF",
        "country" => "Moldova, Republic of",
        "numcode" => "498",
        "flag" => "Moldova-Flag.png",
    ],
    "MDG" => [
        "id" => "MDG",
        "iso" => "MG",
        "name" => "MADAGASCAR",
        "country" => "Madagascar",
        "numcode" => "450",
        "flag" => "Madagascar-Flag.png",
    ],
    "MDV" => [
        "id" => "MDV",
        "iso" => "MV",
        "name" => "MALDIVES",
        "country" => "Maldives",
        "numcode" => "462",
        "flag" => "Maldives-Flag.png",
    ],
    "MEX" => [
        "id" => "MEX",
        "iso" => "MX",
        "name" => "MEXICO",
        "country" => "Mexico",
        "numcode" => "484",
        "flag" => "Mexico-Flag.png",
    ],
    "MHL" => [
        "id" => "MHL",
        "iso" => "MH",
        "name" => "MARSHALL ISLANDS",
        "country" => "Marshall Islands",
        "numcode" => "584",
        "flag" => "Marshall-Islands-Flag.png",
    ],
    "MKD" => [
        "id" => "MKD",
        "iso" => "MK",
        "name" => "MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF",
        "country" => "Macedonia, the Former Yugoslav Republic of",
        "numcode" => "807",
        "flag" => "Macedonia-Flag.png",
    ],
    "MLI" => [
        "id" => "MLI",
        "iso" => "ML",
        "name" => "MALI",
        "country" => "Mali",
        "numcode" => "466",
        "flag" => "Mali-Flag.png",
    ],
    "MLT" => [
        "id" => "MLT",
        "iso" => "MT",
        "name" => "MALTA",
        "country" => "Malta",
        "numcode" => "470",
        "flag" => "Malta-Flag.png",
    ],
    "MMR" => [
        "id" => "MMR",
        "iso" => "MM",
        "name" => "MYANMAR",
        "country" => "Myanmar",
        "numcode" => "104",
        "flag" => "Myanmar-Flag.png",
    ],
    "MNG" => [
        "id" => "MNG",
        "iso" => "MN",
        "name" => "MONGOLIA",
        "country" => "Mongolia",
        "numcode" => "496",
        "flag" => "Mongolia-Flag.png",
    ],
    "MNP" => [
        "id" => "MNP",
        "iso" => "MP",
        "name" => "NORTHERN MARIANA ISLANDS",
        "country" => "Northern Mariana Islands",
        "numcode" => "580",
        "flag" => "United-States-of-America-Flag.png",
    ],
    "MOZ" => [
        "id" => "MOZ",
        "iso" => "MZ",
        "name" => "MOZAMBIQUE",
        "country" => "Mozambique",
        "numcode" => "508",
        "flag" => "Mozambique-Flag.png",
    ],
    "MRT" => [
        "id" => "MRT",
        "iso" => "MR",
        "name" => "MAURITANIA",
        "country" => "Mauritania",
        "numcode" => "478",
        "flag" => "Mauritania-Flag.png",
    ],
    "MSR" => [
        "id" => "MSR",
        "iso" => "MS",
        "name" => "MONTSERRAT",
        "country" => "Montserrat",
        "numcode" => "500",
        "flag" => "Montserrat-Flag.png",
    ],
    "MTQ" => [
        "id" => "MTQ",
        "iso" => "MQ",
        "name" => "MARTINIQUE",
        "country" => "Martinique",
        "numcode" => "474",
        "flag" => "France-Flag.png",
    ],
    "MUS" => [
        "id" => "MUS",
        "iso" => "MU",
        "name" => "MAURITIUS",
        "country" => "Mauritius",
        "numcode" => "480",
        "flag" => "Mauritius-Flag.png",
    ],
    "MWI" => [
        "id" => "MWI",
        "iso" => "MW",
        "name" => "MALAWI",
        "country" => "Malawi",
        "numcode" => "454",
        "flag" => "Malawi-Flag.png",
    ],
    "MYS" => [
        "id" => "MYS",
        "iso" => "MY",
        "name" => "MALAYSIA",
        "country" => "Malaysia",
        "numcode" => "458",
        "flag" => "Malaysia-Flag.png",
    ],
    "NAM" => [
        "id" => "NAM",
        "iso" => "NA",
        "name" => "NAMIBIA",
        "country" => "Namibia",
        "numcode" => "516",
        "flag" => "Namibia-Flag.png",
    ],
    "NCL" => [
        "id" => "NCL",
        "iso" => "NC",
        "name" => "NEW CALEDONIA",
        "country" => "New Caledonia",
        "numcode" => "540",
        "flag" => "France-Flag.png",
    ],
    "NER" => [
        "id" => "NER",
        "iso" => "NE",
        "name" => "NIGER",
        "country" => "Niger",
        "numcode" => "562",
        "flag" => "Niger-Flag.png",
    ],
    "NFK" => [
        "id" => "NFK",
        "iso" => "NF",
        "name" => "NORFOLK ISLAND",
        "country" => "Norfolk Island",
        "numcode" => "574",
        "flag" => "Australia-Flag.png",
    ],
    "NGA" => [
        "id" => "NGA",
        "iso" => "NG",
        "name" => "NIGERIA",
        "country" => "Nigeria",
        "numcode" => "566",
        "flag" => "Nigeria-Flag.png",
    ],
    "NIC" => [
        "id" => "NIC",
        "iso" => "NI",
        "name" => "NICARAGUA",
        "country" => "Nicaragua",
        "numcode" => "558",
        "flag" => "Nicaragua-Flag.png",
    ],
    "NIU" => [
        "id" => "NIU",
        "iso" => "NU",
        "name" => "NIUE",
        "country" => "Niue",
        "numcode" => "570",
        "flag" => "United-Kingdom-Flag.png",
    ],
    "NLD" => [
        "id" => "NLD",
        "iso" => "NL",
        "name" => "NETHERLANDS",
        "country" => "Netherlands",
        "numcode" => "528",
        "flag" => "Netherlands-Flag.png",
    ],
    "NOR" => [
        "id" => "NOR",
        "iso" => "NO",
        "name" => "NORWAY",
        "country" => "Norway",
        "numcode" => "578",
        "flag" => "Norway-Flag.png",
    ],
    "NPL" => [
        "id" => "NPL",
        "iso" => "NP",
        "name" => "NEPAL",
        "country" => "Nepal",
        "numcode" => "524",
        "flag" => "Nepal-Flag.png",
    ],
    "NRU" => [
        "id" => "NRU",
        "iso" => "NR",
        "name" => "NAURU",
        "country" => "Nauru",
        "numcode" => "520",
        "flag" => "Nauru-Flag.png",
    ],
    "NZL" => [
        "id" => "NZL",
        "iso" => "NZ",
        "name" => "NEW ZEALAND",
        "country" => "New Zealand",
        "numcode" => "554",
        "flag" => "New-Zealand-Flag.png",
    ],
    "OMN" => [
        "id" => "OMN",
        "iso" => "OM",
        "name" => "OMAN",
        "country" => "Oman",
        "numcode" => "512",
        "flag" => "Oman-Flag.png",
    ],
    "PAK" => [
        "id" => "PAK",
        "iso" => "PK",
        "name" => "PAKISTAN",
        "country" => "Pakistan",
        "numcode" => "586",
        "flag" => "Pakistan-Flag.png",
    ],
    "PAN" => [
        "id" => "PAN",
        "iso" => "PA",
        "name" => "PANAMA",
        "country" => "Panama",
        "numcode" => "591",
        "flag" => "Panama-Flag.png",
    ],
    "PCN" => [
        "id" => "PCN",
        "iso" => "PN",
        "name" => "PITCAIRN",
        "country" => "Pitcairn",
        "numcode" => "612",
        "flag" => "United-Kingdom-Flag.png",
    ],
    "PER" => [
        "id" => "PER",
        "iso" => "PE",
        "name" => "PERU",
        "country" => "Peru",
        "numcode" => "604",
        "flag" => "Peru-Flag.png",
    ],
    "PHL" => [
        "id" => "PHL",
        "iso" => "PH",
        "name" => "PHILIPPINES",
        "country" => "Philippines",
        "numcode" => "608",
        "flag" => "Philippines-Flag.png",
    ],
    "PLW" => [
        "id" => "PLW",
        "iso" => "PW",
        "name" => "PALAU",
        "country" => "Palau",
        "numcode" => "585",
        "flag" => "Palau-Flag.png",
    ],
    "PNG" => [
        "id" => "PNG",
        "iso" => "PG",
        "name" => "PAPUA NEW GUINEA",
        "country" => "Papua New Guinea",
        "numcode" => "598",
        "flag" => "Papua-New-Guinea-Flag.png",
    ],
    "POL" => [
        "id" => "POL",
        "iso" => "PL",
        "name" => "POLAND",
        "country" => "Poland",
        "numcode" => "616",
        "flag" => "Poland-Flag.png",
    ],
    "PRI" => [
        "id" => "PRI",
        "iso" => "PR",
        "name" => "PUERTO RICO",
        "country" => "Puerto Rico",
        "numcode" => "630",
        "flag" => "Puerto-Rico-Flag.png",
    ],
    "PRK" => [
        "id" => "PRK",
        "iso" => "KP",
        "name" => "KOREA, DEMOCRATIC PEOPLE'S REPUBLIC OF",
        "country" => "Korea, Democratic People's Republic of",
        "numcode" => "408",
        "flag" => "North-Korea-Flag.png",
    ],
    "PRT" => [
        "id" => "PRT",
        "iso" => "PT",
        "name" => "PORTUGAL",
        "country" => "Portugal",
        "numcode" => "620",
        "flag" => "Portugal-Flag.png",
    ],
    "PRY" => [
        "id" => "PRY",
        "iso" => "PY",
        "name" => "PARAGUAY",
        "country" => "Paraguay",
        "numcode" => "600",
        "flag" => "Paraguay-Flag.png",
    ],
    "PS" => [
        "id" => "PS",
        "iso" => "PS",
        "name" => "PALESTINIAN TERRITORY, OCCUPIED",
        "country" => "Palestinian Territory, Occupied",
        "numcode" => "0",
        "flag" => "Palestine-Flag.png",
    ],
    "PYF" => [
        "id" => "PYF",
        "iso" => "PF",
        "name" => "FRENCH POLYNESIA",
        "country" => "French Polynesia",
        "numcode" => "258",
        "flag" => "France-Flag.png",
    ],
    "QAT" => [
        "id" => "QAT",
        "iso" => "QA",
        "name" => "QATAR",
        "country" => "Qatar",
        "numcode" => "634",
        "flag" => "Qatar-Flag.png",
    ],
    "REU" => [
        "id" => "REU",
        "iso" => "RE",
        "name" => "REUNION",
        "country" => "Reunion",
        "numcode" => "638",
        "flag" => "France-Flag.png",
    ],
    "ROM" => [
        "id" => "ROM",
        "iso" => "RO",
        "name" => "ROMANIA",
        "country" => "Romania",
        "numcode" => "642",
        "flag" => "Romania-Flag.png",
    ],
    "RUS" => [
        "id" => "RUS",
        "iso" => "RU",
        "name" => "RUSSIAN FEDERATION",
        "country" => "Russian Federation",
        "numcode" => "643",
        "flag" => "Russian-Federation-Flag.png",
    ],
    "RWA" => [
        "id" => "RWA",
        "iso" => "RW",
        "name" => "RWANDA",
        "country" => "Rwanda",
        "numcode" => "646",
        "flag" => "Rwanda-Flag.png",
    ],
    "SAU" => [
        "id" => "SAU",
        "iso" => "SA",
        "name" => "SAUDI ARABIA",
        "country" => "Saudi Arabia",
        "numcode" => "682",
        "flag" => "Saudi-Arabia-Flag.png",
    ],
    "SDN" => [
        "id" => "SDN",
        "iso" => "SD",
        "name" => "SUDAN",
        "country" => "Sudan",
        "numcode" => "736",
        "flag" => "Sudan-Flag.png",
    ],
    "SEN" => [
        "id" => "SEN",
        "iso" => "SN",
        "name" => "SENEGAL",
        "country" => "Senegal",
        "numcode" => "686",
        "flag" => "Senegal-Flag.png",
    ],
    "SGP" => [
        "id" => "SGP",
        "iso" => "SG",
        "name" => "SINGAPORE",
        "country" => "Singapore",
        "numcode" => "702",
        "flag" => "Singapore-Flag.png",
    ],
    "SHN" => [
        "id" => "SHN",
        "iso" => "SH",
        "name" => "SAINT HELENA",
        "country" => "Saint Helena",
        "numcode" => "654",
        "flag" => "United-Kingdom-Flag.png",
    ],
    "SJM" => [
        "id" => "SJM",
        "iso" => "SJ",
        "name" => "SVALBARD AND JAN MAYEN",
        "country" => "Svalbard and Jan Mayen",
        "numcode" => "744",
        "flag" => "Norway-Flag.png",
    ],
    "SLB" => [
        "id" => "SLB",
        "iso" => "SB",
        "name" => "SOLOMON ISLANDS",
        "country" => "Solomon Islands",
        "numcode" => "90",
        "flag" => "Solomon-Islands-Flag.png",
    ],
    "SLE" => [
        "id" => "SLE",
        "iso" => "SL",
        "name" => "SIERRA LEONE",
        "country" => "Sierra Leone",
        "numcode" => "694",
        "flag" => "Sierra-Leone-Flag.png",
    ],
    "SLV" => [
        "id" => "SLV",
        "iso" => "SV",
        "name" => "EL SALVADOR",
        "country" => "El Salvador",
        "numcode" => "222",
        "flag" => "El-Salvador-Flag.png",
    ],
    "SMR" => [
        "id" => "SMR",
        "iso" => "SM",
        "name" => "SAN MARINO",
        "country" => "San Marino",
        "numcode" => "674",
        "flag" => "San-Marino-Flag.png",
    ],
    "SOM" => [
        "id" => "SOM",
        "iso" => "SO",
        "name" => "SOMALIA",
        "country" => "Somalia",
        "numcode" => "706",
        "flag" => "Somalia-Flag.png",
    ],
    "SPM" => [
        "id" => "SPM",
        "iso" => "PM",
        "name" => "SAINT PIERRE AND MIQUELON",
        "country" => "Saint Pierre and Miquelon",
        "numcode" => "666",
        "flag" => "France-Flag.png",
    ],
    "STP" => [
        "id" => "STP",
        "iso" => "ST",
        "name" => "SAO TOME AND PRINCIPE",
        "country" => "Sao Tome and Principe",
        "numcode" => "678",
        "flag" => "Sao-Tome-and-Principe-Flag.png",
    ],
    "SUR" => [
        "id" => "SUR",
        "iso" => "SR",
        "name" => "SURINAME",
        "country" => "Suriname",
        "numcode" => "740",
        "flag" => "Suriname-Flag.png",
    ],
    "SVK" => [
        "id" => "SVK",
        "iso" => "SK",
        "name" => "SLOVAKIA",
        "country" => "Slovakia",
        "numcode" => "703",
        "flag" => "Slovakia-Flag.png",
    ],
    "SVN" => [
        "id" => "SVN",
        "iso" => "SI",
        "name" => "SLOVENIA",
        "country" => "Slovenia",
        "numcode" => "705",
        "flag" => "Slovenia-Flag.png",
    ],
    "SWE" => [
        "id" => "SWE",
        "iso" => "SE",
        "name" => "SWEDEN",
        "country" => "Sweden",
        "numcode" => "752",
        "flag" => "Sweden-Flag.png",
    ],
    "SWZ" => [
        "id" => "SWZ",
        "iso" => "SZ",
        "name" => "SWAZILAND",
        "country" => "Swaziland",
        "numcode" => "748",
        "flag" => "Swaziland-Flag.png",
    ],
    "SYC" => [
        "id" => "SYC",
        "iso" => "SC",
        "name" => "SEYCHELLES",
        "country" => "Seychelles",
        "numcode" => "690",
        "flag" => "Seychelles-Flag.png",
    ],
    "SYR" => [
        "id" => "SYR",
        "iso" => "SY",
        "name" => "SYRIAN ARAB REPUBLIC",
        "country" => "Syrian Arab Republic",
        "numcode" => "760",
        "flag" => "Syria-Flag.png",
    ],
    "TCA" => [
        "id" => "TCA",
        "iso" => "TC",
        "name" => "TURKS AND CAICOS ISLANDS",
        "country" => "Turks and Caicos Islands",
        "numcode" => "796",
        "flag" => "Turks-and-Caicos-Islands-Flag.png",
    ],
    "TCD" => [
        "id" => "TCD",
        "iso" => "TD",
        "name" => "CHAD",
        "country" => "Chad",
        "numcode" => "148",
        "flag" => "Chad-Flag.png",
    ],
    "TF" => [
        "id" => "TF",
        "iso" => "TF",
        "name" => "FRENCH SOUTHERN TERRITORIES",
        "country" => "French Southern Territories",
        "numcode" => "0",
        "flag" => "France-Flag.png",
    ],
    "TGO" => [
        "id" => "TGO",
        "iso" => "TG",
        "name" => "TOGO",
        "country" => "Togo",
        "numcode" => "768",
        "flag" => "Togo-Flag.png",
    ],
    "THA" => [
        "id" => "THA",
        "iso" => "TH",
        "name" => "THAILAND",
        "country" => "Thailand",
        "numcode" => "764",
        "flag" => "Thailand-Flag.png",
    ],
    "TJK" => [
        "id" => "TJK",
        "iso" => "TJ",
        "name" => "TAJIKISTAN",
        "country" => "Tajikistan",
        "numcode" => "762",
        "flag" => "Tajikistan-Flag.png",
    ],
    "TKL" => [
        "id" => "TKL",
        "iso" => "TK",
        "name" => "TOKELAU",
        "country" => "Tokelau",
        "numcode" => "772",
        "flag" => "New-Zealand-Flag.png",
    ],
    "TKM" => [
        "id" => "TMK",
        "iso" => "TM",
        "name" => "TURKMENISTAN",
        "country" => "Turkmenistan",
        "numcode" => "795",
        "flag" => "Turkmenistan-Flag.png",
    ],
    "TL" => [
        "id" => "TL",
        "iso" => "TL",
        "name" => "TIMOR-LESTE",
        "country" => "Timor-Leste",
        "numcode" => "0",
        "flag" => "Timor-Leste-Flag.png",
    ],
    "TON" => [
        "id" => "TON",
        "iso" => "TO",
        "name" => "TONGA",
        "country" => "Tonga",
        "numcode" => "776",
        "flag" => "Tonga-Flag.png",
    ],
    "TTO" => [
        "id" => "TTO",
        "iso" => "TT",
        "name" => "TRINIDAD AND TOBAGO",
        "country" => "Trinidad and Tobago",
        "numcode" => "780",
        "flag" => "Trinidad-and-Tobago-Flag.png",
    ],
    "TUN" => [
        "id" => "TUN",
        "iso" => "TN",
        "name" => "TUNISIA",
        "country" => "Tunisia",
        "numcode" => "788",
        "flag" => "Tunisia-Flag.png",
    ],
    "TUR" => [
        "id" => "TUR",
        "iso" => "TR",
        "name" => "TURKEY",
        "country" => "Turkey",
        "numcode" => "792",
        "flag" => "Turkey-Flag.png",
    ],
    "TUV" => [
        "id" => "TUV",
        "iso" => "TV",
        "name" => "TUVALU",
        "country" => "Tuvalu",
        "numcode" => "798",
        "flag" => "Tuvalu-Flag.png",
    ],
    "TWN" => [
        "id" => "TWN",
        "iso" => "TW",
        "name" => "TAIWAN, PROVINCE OF CHINA",
        "country" => "Taiwan, Province of China",
        "numcode" => "158",
        "flag" => "Taiwan-Flag.png",
    ],
    "TZA" => [
        "id" => "TZA",
        "iso" => "TZ",
        "name" => "TANZANIA, UNITED REPUBLIC OF",
        "country" => "Tanzania, United Republic of",
        "numcode" => "834",
        "flag" => "Tanzania-Flag.png",
    ],
    "UGA" => [
        "id" => "UGA",
        "iso" => "UG",
        "name" => "UGANDA",
        "country" => "Uganda",
        "numcode" => "800",
        "flag" => "Uganda-Flag.png",
    ],
    "UKR" => [
        "id" => "UKR",
        "iso" => "UA",
        "name" => "UKRAINE",
        "country" => "Ukraine",
        "numcode" => "804",
        "flag" => "Ukraine-Flag.png",
    ],
    "UM" => [
        "id" => "UM",
        "iso" => "UM",
        "name" => "UNITED STATES MINOR OUTLYING ISLANDS",
        "country" => "United States Minor Outlying Islands",
        "numcode" => "0",
        "flag" => "United-States-of-America-Flag.png",
    ],
    "URY" => [
        "id" => "URY",
        "iso" => "UY",
        "name" => "URUGUAY",
        "country" => "Uruguay",
        "numcode" => "858",
        "flag" => "Uruguay-Flag.png",
    ],
    "USA" => [
        "id" => "USA",
        "iso" => "US",
        "name" => "UNITED STATES",
        "country" => "United States",
        "numcode" => "840",
        "flag" => "United-States-of-America-Flag.png",
    ],
    "UZB" => [
        "id" => "UZB",
        "iso" => "UZ",
        "name" => "UZBEKISTAN",
        "country" => "Uzbekistan",
        "numcode" => "860",
        "flag" => "Uzbekistan-Flag.png",
    ],
    "VAT" => [
        "id" => "VAT",
        "iso" => "VA",
        "name" => "HOLY SEE (VATICAN CITY STATE]",
        "country" => "Holy See (Vatican City State]",
        "numcode" => "336",
        "flag" => "Vatican-City-Flag.png",
    ],
    "VCT" => [
        "id" => "VCT",
        "iso" => "VC",
        "name" => "SAINT VINCENT AND THE GRENADINES",
        "country" => "Saint Vincent and the Grenadines",
        "numcode" => "670",
        "flag" => "St-Vincent-and-the-Grenadines-Flag.png",
    ],
    "VEN" => [
        "id" => "VEN",
        "iso" => "VE",
        "name" => "VENEZUELA",
        "country" => "Venezuela",
        "numcode" => "862",
        "flag" => "Venezuela-Flag.png",
    ],
    "VGB" => [
        "id" => "VGB",
        "iso" => "VG",
        "name" => "VIRGIN ISLANDS, BRITISH",
        "country" => "Virgin Islands, British",
        "numcode" => "92",
        "flag" => "Virgin-Islands-British-Flag.png",
    ],
    "VIR" => [
        "id" => "VIR",
        "iso" => "VI",
        "name" => "VIRGIN ISLANDS, U.S.",
        "country" => "Virgin Islands, U.s.",
        "numcode" => "850",
        "flag" => "Virgin-Islands-US-Flag.png",
    ],
    "VNM" => [
        "id" => "VNM",
        "iso" => "VN",
        "name" => "VIET NAM",
        "country" => "Viet Nam",
        "numcode" => "704",
        "flag" => "Viet-Nam-Flag.png",
    ],
    "VUT" => [
        "id" => "VUT",
        "iso" => "VU",
        "name" => "VANUATU",
        "country" => "Vanuatu",
        "numcode" => "548",
        "flag" => "Vanutau-Flag.png",
    ],
    "WLF" => [
        "id" => "WLF",
        "iso" => "WF",
        "name" => "WALLIS AND FUTUNA",
        "country" => "Wallis and Futuna",
        "numcode" => "876",
        "flag" => "France-Flag.png",
    ],
    "WSM" => [
        "id" => "WSM",
        "iso" => "WS",
        "name" => "SAMOA",
        "country" => "Samoa",
        "numcode" => "882",
        "flag" => "Samoa-Flag.png",
    ],
    "YEM" => [
        "id" => "YEM",
        "iso" => "YE",
        "name" => "YEMEN",
        "country" => "Yemen",
        "numcode" => "887",
        "flag" => "Yemen-Flag.png",
    ],
    "YT" => [
        "id" => "YT",
        "iso" => "YT",
        "name" => "MAYOTTE",
        "country" => "Mayotte",
        "numcode" => "0",
        "flag" => "France-Flag.png",
    ],
    "ZAF" => [
        "id" => "ZAF",
        "iso" => "ZA",
        "name" => "SOUTH AFRICA",
        "country" => "South Africa",
        "numcode" => "710",
        "flag" => "South-Africa-Flag.png",
    ],
    "ZMB" => [
        "id" => "ZMB",
        "iso" => "ZM",
        "name" => "ZAMBIA",
        "country" => "Zambia",
        "numcode" => "894",
        "flag" => "Zambia-Flag.png",
    ],
    "ZWE" => [
        "id" => "ZWE",
        "iso" => "ZW",
        "name" => "ZIMBABWE",
        "country" => "Zimbabwe",
        "numcode" => "716",
        "flag" => "Zimbabwe-Flag.png",
    ],
];