<?php

declare(strict_types=1);

namespace Del\Factory;

use Del\Entity\Country;
use Del\Repository\CountryRepository;

class CountryList
{
    private array $countries;

    public function __construct()
    {
        $this->countries = [
            'AF' => [
                'id' => 'AFG',
                'iso' => 'AF',
                'name' => 'Afghanistan',
                'numcode' => 4,
                'flag' => 'Afghanistan-Flag.png',
            ],
            'AL' => [
                'id' => 'ALB',
                'iso' => 'AL',
                'name' => 'Albania',
                'numcode' => 8,
                'flag' => 'Albania-Flag.png',
            ],
            'DZ' => [
                'id' => 'DZA',
                'iso' => 'DZ',
                'name' => 'Algeria',
                'numcode' => 12,
                'flag' => 'Algeria-Flag.png',
            ],
            'AS' => [
                'id' => 'ASM',
                'iso' => 'AS',
                'name' => 'American Samoa',
                'numcode' => 16,
                'flag' => 'American-Samoa-Flag.png',
            ],
            'AD' => [
                'id' => 'AND',
                'iso' => 'AD',
                'name' => 'Andorra',
                'numcode' => 20,
                'flag' => 'Andorra-Flag.png',
            ],
            'AO' => [
                'id' => 'AGO',
                'iso' => 'AO',
                'name' => 'Angola',
                'numcode' => 24,
                'flag' => 'Angola-Flag.png',
            ],
            'AI' => [
                'id' => 'AIA',
                'iso' => 'AI',
                'name' => 'Anguilla',
                'numcode' => 660,
                'flag' => 'Anguilla-Flag.png',
            ],
            'AQ' => [
                'id' => 'AQ',
                'iso' => 'AQ',
                'name' => 'Antarctica',
                'numcode' => 0,
                'flag' => 'Antarctica-Flag.png',
            ],
            'AG' => [
                'id' => 'ATG',
                'iso' => 'AG',
                'name' => 'Antigua and Barbuda',
                'numcode' => 28,
                'flag' => 'Antigua-and-Barbuda-Flag.png',
            ],
            'AR' => [
                'id' => 'ARG',
                'iso' => 'AR',
                'name' => 'Argentina',
                'numcode' => 32,
                'flag' => 'Argentina-Flag.png',
            ],
            'AM' => [
                'id' => 'ARM',
                'iso' => 'AM',
                'name' => 'Armenia',
                'numcode' => 51,
                'flag' => 'Armenia-Flag.png',
            ],
            'AW' => [
                'id' => 'ABW',
                'iso' => 'AW',
                'name' => 'Aruba',
                'numcode' => 533,
                'flag' => 'Aruba-Flag.png',
            ],
            'AU' => [
                'id' => 'AUS',
                'iso' => 'AU',
                'name' => 'Australia',
                'numcode' => 36,
                'flag' => 'Australia-Flag.png',
            ],
            'AT' => [
                'id' => 'AUT',
                'iso' => 'AT',
                'name' => 'Austria',
                'numcode' => 40,
                'flag' => 'Austria-Flag.png',
            ],
            'AZ' => [
                'id' => 'AZE',
                'iso' => 'AZ',
                'name' => 'Azerbaijan',
                'numcode' => 31,
                'flag' => 'Azerbaijan-Flag.png',
            ],
            'BS' => [
                'id' => 'BHS',
                'iso' => 'BS',
                'name' => 'Bahamas',
                'numcode' => 44,
                'flag' => 'Bahamas-Flag.png',
            ],
            'BH' => [
                'id' => 'BHR',
                'iso' => 'BH',
                'name' => 'Bahrain',
                'numcode' => 48,
                'flag' => 'Bahrain-Flag.png',
            ],
            'BD' => [
                'id' => 'BGD',
                'iso' => 'BD',
                'name' => 'Bangladesh',
                'numcode' => 50,
                'flag' => 'Bangladesh-Flag.png',
            ],
            'BB' => [
                'id' => 'BRB',
                'iso' => 'BB',
                'name' => 'Barbados',
                'numcode' => 52,
                'flag' => 'Barbados-Flag.png',
            ],
            'BY' => [
                'id' => 'BLR',
                'iso' => 'BY',
                'name' => 'Belarus',
                'numcode' => 112,
                'flag' => 'Belarus-Flag.png',
            ],
            'BE' => [
                'id' => 'BEL',
                'iso' => 'BE',
                'name' => 'Belgium',
                'numcode' => 56,
                'flag' => 'Belgium-Flag.png',
            ],
            'BZ' => [
                'id' => 'BLZ',
                'iso' => 'BZ',
                'name' => 'Belize',
                'numcode' => 84,
                'flag' => 'Belize-Flag.png',
            ],
            'BJ' => [
                'id' => 'BEN',
                'iso' => 'BJ',
                'name' => 'Benin',
                'numcode' => 204,
                'flag' => 'Benin-Flag.png',
            ],
            'BM' => [
                'id' => 'BMU',
                'iso' => 'BM',
                'name' => 'Bermuda',
                'numcode' => 60,
                'flag' => 'Bermuda-Flag.png',
            ],
            'BT' => [
                'id' => 'BTN',
                'iso' => 'BT',
                'name' => 'Bhutan',
                'numcode' => 64,
                'flag' => 'Bhutan-Flag.png',
            ],
            'BO' => [
                'id' => 'BOL',
                'iso' => 'BO',
                'name' => 'Bolivia',
                'numcode' => 68,
                'flag' => 'Bolivia-Flag.png',
            ],
            'BA' => [
                'id' => 'BIH',
                'iso' => 'BA',
                'name' => 'Bosnia and Herzegovina',
                'numcode' => 70,
                'flag' => 'Bosnia-and-Herzegovina-Flag.png',
            ],
            'BW' => [
                'id' => 'BWA',
                'iso' => 'BW',
                'name' => 'Botswana',
                'numcode' => 72,
                'flag' => 'Botswana-Flag.png',
            ],
            'BR' => [
                'id' => 'BRA',
                'iso' => 'BR',
                'name' => 'Brazil',
                'numcode' => 76,
                'flag' => 'Brazil-Flag.png',
            ],
            'BN' => [
                'id' => 'BRN',
                'iso' => 'BN',
                'name' => 'Brunei Darussalam',
                'numcode' => 96,
                'flag' => 'Brunei-Flag.png',
            ],
            'BG' => [
                'id' => 'BGR',
                'iso' => 'BG',
                'name' => 'Bulgaria',
                'numcode' => 100,
                'flag' => 'Bulgaria-Flag.png',
            ],
            'BF' => [
                'id' => 'BFA',
                'iso' => 'BF',
                'name' => 'Burkina Faso',
                'numcode' => 854,
                'flag' => 'Burkina-Faso-Flag.png',
            ],
            'BI' => [
                'id' => 'BDI',
                'iso' => 'BI',
                'name' => 'Burundi',
                'numcode' => 108,
                'flag' => 'Burundi-Flag.png',
            ],
            'KH' => [
                'id' => 'KHM',
                'iso' => 'KH',
                'name' => 'Cambodia',
                'numcode' => 116,
                'flag' => 'Cambodia-Flag.png',
            ],
            'CM' => [
                'id' => 'CMR',
                'iso' => 'CM',
                'name' => 'Cameroon',
                'numcode' => 120,
                'flag' => 'Cameroon-Flag.png',
            ],
            'CA' => [
                'id' => 'CAN',
                'iso' => 'CA',
                'name' => 'Canada',
                'numcode' => 124,
                'flag' => 'Canada-Flag.png',
            ],
            'CV' => [
                'id' => 'CPV',
                'iso' => 'CV',
                'name' => 'Cape Verde',
                'numcode' => 132,
                'flag' => 'Cape-Verde-Flag.png',
            ],
            'KY' => [
                'id' => 'CYM',
                'iso' => 'KY',
                'name' => 'Cayman Islands',
                'numcode' => 136,
                'flag' => 'Cayman-Islands-Flag.png',
            ],
            'CF' => [
                'id' => 'CAF',
                'iso' => 'CF',
                'name' => 'Central African Republic',
                'numcode' => 140,
                'flag' => 'Central-African-Republic-Flag.png',
            ],
            'TD' => [
                'id' => 'TCD',
                'iso' => 'TD',
                'name' => 'Chad',
                'numcode' => 148,
                'flag' => 'Chad-Flag.png',
            ],
            'CL' => [
                'id' => 'CHL',
                'iso' => 'CL',
                'name' => 'Chile',
                'numcode' => 152,
                'flag' => 'Chile-Flag.png',
            ],
            'CN' => [
                'id' => 'CHN',
                'iso' => 'CN',
                'name' => 'China',
                'numcode' => 156,
                'flag' => 'China-Flag.png',
            ],
            'CO' => [
                'id' => 'COL',
                'iso' => 'CO',
                'name' => 'Colombia',
                'numcode' => 170,
                'flag' => 'Colombia-Flag.png',
            ],
            'KM' => [
                'id' => 'COM',
                'iso' => 'KM',
                'name' => 'Comoros',
                'numcode' => 174,
                'flag' => 'Comoros-Flag.png',
            ],
            'CG' => [
                'id' => 'COG',
                'iso' => 'CG',
                'name' => 'Congo',
                'numcode' => 178,
                'flag' => 'Congo-Brazzaville-Flag.png',
            ],
            'CD' => [
                'id' => 'COD',
                'iso' => 'CD',
                'name' => 'Congo, the Democratic Republic of the',
                'numcode' => 180,
                'flag' => 'Congo-Kinshasa-Flag.png',
            ],
            'CK' => [
                'id' => 'COK',
                'iso' => 'CK',
                'name' => 'Cook Islands',
                'numcode' => 184,
                'flag' => 'Cook-Islands-Flag.png',
            ],
            'CR' => [
                'id' => 'CRI',
                'iso' => 'CR',
                'name' => 'Costa Rica',
                'numcode' => 188,
                'flag' => 'Costa-Rica-Flag.png',
            ],
            'CI' => [
                'id' => 'CIV',
                'iso' => 'CI',
                'name' => 'Cote D\'Ivoire',
                'numcode' => 384,
                'flag' => 'Cote-DIvoire-Flag.png',
            ],
            'HR' => [
                'id' => 'HRV',
                'iso' => 'HR',
                'name' => 'Croatia',
                'numcode' => 191,
                'flag' => 'Croatia-Flag.png',
            ],
            'CU' => [
                'id' => 'CUB',
                'iso' => 'CU',
                'name' => 'Cuba',
                'numcode' => 192,
                'flag' => 'Cuba-Flag.png',
            ],
            'CY' => [
                'id' => 'CYP',
                'iso' => 'CY',
                'name' => 'Cyprus',
                'numcode' => 196,
                'flag' => 'Cyprus-Flag.png',
            ],
            'CZ' => [
                'id' => 'CZE',
                'iso' => 'CZ',
                'name' => 'Czech Republic',
                'numcode' => 203,
                'flag' => 'Czech-Republic-Flag.png',
            ],
            'DK' => [
                'id' => 'DNK',
                'iso' => 'DK',
                'name' => 'Denmark',
                'numcode' => 208,
                'flag' => 'Denmark-Flag.png',
            ],
            'DJ' => [
                'id' => 'DJI',
                'iso' => 'DJ',
                'name' => 'Djibouti',
                'numcode' => 262,
                'flag' => 'Djibouti-Flag.png',
            ],
            'DM' => [
                'id' => 'DMA',
                'iso' => 'DM',
                'name' => 'Dominica',
                'numcode' => 212,
                'flag' => 'Dominica-Flag.png',
            ],
            'DO' => [
                'id' => 'DOM',
                'iso' => 'DO',
                'name' => 'Dominican Republic',
                'numcode' => 214,
                'flag' => 'Dominican-Republic-Flag.png',
            ],
            'EC' => [
                'id' => 'ECU',
                'iso' => 'EC',
                'name' => 'Ecuador',
                'numcode' => 218,
                'flag' => 'Ecuador-Flag.png',
            ],
            'EG' => [
                'id' => 'EGY',
                'iso' => 'EG',
                'name' => 'Egypt',
                'numcode' => 818,
                'flag' => 'Egypt-Flag.png',
            ],
            'SV' => [
                'id' => 'SLV',
                'iso' => 'SV',
                'name' => 'El Salvador',
                'numcode' => 222,
                'flag' => 'El-Salvador-Flag.png',
            ],
            'GQ' => [
                'id' => 'GNQ',
                'iso' => 'GQ',
                'name' => 'Equatorial Guinea',
                'numcode' => 226,
                'flag' => 'Equatorial-Guinea-Flag.png',
            ],
            'ER' => [
                'id' => 'ERI',
                'iso' => 'ER',
                'name' => 'Eritrea',
                'numcode' => 232,
                'flag' => 'Eritrea-Flag.png',
            ],
            'EE' => [
                'id' => 'EST',
                'iso' => 'EE',
                'name' => 'Estonia',
                'numcode' => 233,
                'flag' => 'Estonia-Flag.png',
            ],
            'ET' => [
                'id' => 'ETH',
                'iso' => 'ET',
                'name' => 'Ethiopia',
                'numcode' => 231,
                'flag' => 'Ethiopia-Flag.png',
            ],
            'FK' => [
                'id' => 'FLK',
                'iso' => 'FK',
                'name' => 'Falkland Islands (Malvinas]',
                'numcode' => 238,
                'flag' => 'United-Kingdom-Flag.png',
            ],
            'FO' => [
                'id' => 'FRO',
                'iso' => 'FO',
                'name' => 'Faroe Islands',
                'numcode' => 234,
                'flag' => 'Faroes-Flag.png',
            ],
            'FJ' => [
                'id' => 'FJI',
                'iso' => 'FJ',
                'name' => 'Fiji',
                'numcode' => 242,
                'flag' => 'Fiji-Flag.png',
            ],
            'FI' => [
                'id' => 'FIN',
                'iso' => 'FI',
                'name' => 'Finland',
                'numcode' => 246,
                'flag' => 'Finland-Flag.png',
            ],
            'FR' => [
                'id' => 'FRA',
                'iso' => 'FR',
                'name' => 'France',
                'numcode' => 250,
                'flag' => 'France-Flag.png',
            ],
            'GF' => [
                'id' => 'GUF',
                'iso' => 'GF',
                'name' => 'French Guiana',
                'numcode' => 254,
                'flag' => 'France-Flag.png',
            ],
            'PF' => [
                'id' => 'PYF',
                'iso' => 'PF',
                'name' => 'French Polynesia',
                'numcode' => 258,
                'flag' => 'France-Flag.png',
            ],
            'TF' => [
                'id' => 'TF',
                'iso' => 'TF',
                'name' => 'French Southern Territories',
                'numcode' => 0,
                'flag' => 'France-Flag.png',
            ],
            'GA' => [
                'id' => 'GAB',
                'iso' => 'GA',
                'name' => 'Gabon',
                'numcode' => 266,
                'flag' => 'Gabon-Flag.png',
            ],
            'GM' => [
                'id' => 'GMB',
                'iso' => 'GM',
                'name' => 'Gambia',
                'numcode' => 270,
                'flag' => 'Gambia-Flag.png',
            ],
            'GE' => [
                'id' => 'GEO',
                'iso' => 'GE',
                'name' => 'Georgia',
                'numcode' => 268,
                'flag' => 'Georgia-Flag.png',
            ],
            'DE' => [
                'id' => 'DEU',
                'iso' => 'DE',
                'name' => 'Germany',
                'numcode' => 276,
                'flag' => 'Germany-Flag.png',
            ],
            'GH' => [
                'id' => 'GHA',
                'iso' => 'GH',
                'name' => 'Ghana',
                'numcode' => 288,
                'flag' => 'Ghana-Flag.png',
            ],
            'GI' => [
                'id' => 'GIB',
                'iso' => 'GI',
                'name' => 'Gibraltar',
                'numcode' => 292,
                'flag' => 'Gibraltar-Flag.png',
            ],
            'GR' => [
                'id' => 'GRC',
                'iso' => 'GR',
                'name' => 'Greece',
                'numcode' => 300,
                'flag' => 'Greece-Flag.png',
            ],
            'GL' => [
                'id' => 'GRL',
                'iso' => 'GL',
                'name' => 'Greenland',
                'numcode' => 304,
                'flag' => 'Denmark-Flag.png',
            ],
            'GD' => [
                'id' => 'GRD',
                'iso' => 'GD',
                'name' => 'Grenada',
                'numcode' => 308,
                'flag' => 'Grenada-Flag.png',
            ],
            'GP' => [
                'id' => 'GLP',
                'iso' => 'GP',
                'name' => 'Guadeloupe',
                'numcode' => 312,
                'flag' => 'France-Flag.png',
            ],
            'GU' => [
                'id' => 'GUM',
                'iso' => 'GU',
                'name' => 'Guam',
                'numcode' => 316,
                'flag' => 'Guam-Flag.png',
            ],
            'GT' => [
                'id' => 'GTM',
                'iso' => 'GT',
                'name' => 'Guatemala',
                'numcode' => 320,
                'flag' => 'Guatemala-Flag.png',
            ],
            'GN' => [
                'id' => 'GIN',
                'iso' => 'GN',
                'name' => 'Guinea',
                'numcode' => 324,
                'flag' => 'Guinea-Flag.png',
            ],
            'GW' => [
                'id' => 'GNB',
                'iso' => 'GW',
                'name' => 'Guinea-Bissau',
                'numcode' => 624,
                'flag' => 'Guinea-Bissau-Flag.png',
            ],
            'GY' => [
                'id' => 'GUY',
                'iso' => 'GY',
                'name' => 'Guyana',
                'numcode' => 328,
                'flag' => 'Guyana-Flag.png',
            ],
            'HT' => [
                'id' => 'HTI',
                'iso' => 'HT',
                'name' => 'Haiti',
                'numcode' => 332,
                'flag' => 'Haiti-Flag.png',
            ],
            'HM' => [
                'id' => 'HM',
                'iso' => 'HM',
                'name' => 'Heard Island and Mcdonald Islands',
                'numcode' => 0,
                'flag' => 'Australia-Flag.png',
            ],
            'VA' => [
                'id' => 'VAT',
                'iso' => 'VA',
                'name' => 'Holy See (Vatican City State]',
                'numcode' => 336,
                'flag' => 'Vatican-City-Flag.png',
            ],
            'HN' => [
                'id' => 'HND',
                'iso' => 'HN',
                'name' => 'Honduras',
                'numcode' => 340,
                'flag' => 'Honduras-Flag.png',
            ],
            'HK' => [
                'id' => 'HKG',
                'iso' => 'HK',
                'name' => 'Hong Kong',
                'numcode' => 344,
                'flag' => 'Hong-Kong-Flag.png',
            ],
            'HU' => [
                'id' => 'HUN',
                'iso' => 'HU',
                'name' => 'Hungary',
                'numcode' => 348,
                'flag' => 'Hungary-Flag.png',
            ],
            'IS' => [
                'id' => 'ISL',
                'iso' => 'IS',
                'name' => 'Iceland',
                'numcode' => 352,
                'flag' => 'Iceland-Flag.png',
            ],
            'IN' => [
                'id' => 'IND',
                'iso' => 'IN',
                'name' => 'India',
                'numcode' => 356,
                'flag' => 'India-Flag.png',
            ],
            'ID' => [
                'id' => 'IDN',
                'iso' => 'ID',
                'name' => 'Indonesia',
                'numcode' => 360,
                'flag' => 'Indonezia-Flag.png',
            ],
            'IR' => [
                'id' => 'IRN',
                'iso' => 'IR',
                'name' => 'Iran, Islamic Republic of',
                'numcode' => 364,
                'flag' => 'Iran-Flag.png',
            ],
            'IQ' => [
                'id' => 'IRQ',
                'iso' => 'IQ',
                'name' => 'Iraq',
                'numcode' => 368,
                'flag' => 'Iraq-Flag.png',
            ],
            'IE' => [
                'id' => 'IRL',
                'iso' => 'IE',
                'name' => 'Ireland',
                'numcode' => 372,
                'flag' => 'Ireland-Flag.png',
            ],
            'IL' => [
                'id' => 'ISR',
                'iso' => 'IL',
                'name' => 'Israel',
                'numcode' => 376,
                'flag' => 'Israel-Flag.png',
            ],
            'IT' => [
                'id' => 'ITA',
                'iso' => 'IT',
                'name' => 'Italy',
                'numcode' => 380,
                'flag' => 'Italy-Flag.png',
            ],
            'JM' => [
                'id' => 'JAM',
                'iso' => 'JM',
                'name' => 'Jamaica',
                'numcode' => 388,
                'flag' => 'Jamaica-Flag.png',
            ],
            'JP' => [
                'id' => 'JPN',
                'iso' => 'JP',
                'name' => 'Japan',
                'numcode' => 392,
                'flag' => 'Japan-Flag.png',
            ],
            'JO' => [
                'id' => 'JOR',
                'iso' => 'JO',
                'name' => 'Jordan',
                'numcode' => 400,
                'flag' => 'Jordan-Flag.png',
            ],
            'KZ' => [
                'id' => 'KAZ',
                'iso' => 'KZ',
                'name' => 'Kazakhstan',
                'numcode' => 398,
                'flag' => 'Kazakhstan-Flag.png',
            ],
            'KE' => [
                'id' => 'KEN',
                'iso' => 'KE',
                'name' => 'Kenya',
                'numcode' => 404,
                'flag' => 'Kenya-Flag.png',
            ],
            'KI' => [
                'id' => 'KIR',
                'iso' => 'KI',
                'name' => 'Kiribati',
                'numcode' => 296,
                'flag' => 'Kiribati-Flag.png',
            ],
            'KP' => [
                'id' => 'PRK',
                'iso' => 'KP',
                'name' => 'Korea, Democratic People\'s Republic of',
                'numcode' => 408,
                'flag' => 'North-Korea-Flag.png',
            ],
            'KR' => [
                'id' => 'KOR',
                'iso' => 'KR',
                'name' => 'Korea, Republic of',
                'numcode' => 410,
                'flag' => 'South-Korea-Flag.png',
            ],
            'KW' => [
                'id' => 'KWT',
                'iso' => 'KW',
                'name' => 'Kuwait',
                'numcode' => 414,
                'flag' => 'Kuwait-Flag.png',
            ],
            'KG' => [
                'id' => 'KGZ',
                'iso' => 'KG',
                'name' => 'Kyrgyzstan',
                'numcode' => 417,
                'flag' => 'Kyrgyzstan-Flag.png',
            ],
            'LA' => [
                'id' => 'LAO',
                'iso' => 'LA',
                'name' => 'Lao People\'s Democratic Republic',
                'numcode' => 418,
                'flag' => 'Laos-Flag.png',
            ],
            'LV' => [
                'id' => 'LVA',
                'iso' => 'LV',
                'name' => 'Latvia',
                'numcode' => 428,
                'flag' => 'Latvia-Flag.png',
            ],
            'LB' => [
                'id' => 'LBN',
                'iso' => 'LB',
                'name' => 'Lebanon',
                'numcode' => 422,
                'flag' => 'Lebanon-Flag.png',
            ],
            'LS' => [
                'id' => 'LSO',
                'iso' => 'LS',
                'name' => 'Lesotho',
                'numcode' => 426,
                'flag' => 'Lesotho-Flag.png',
            ],
            'LR' => [
                'id' => 'LBR',
                'iso' => 'LR',
                'name' => 'Liberia',
                'numcode' => 430,
                'flag' => 'Liberia-Flag.png',
            ],
            'LY' => [
                'id' => 'LBY',
                'iso' => 'LY',
                'name' => 'Libyan Arab Jamahiriya',
                'numcode' => 434,
                'flag' => 'Libya-Flag.png',
            ],
            'LI' => [
                'id' => 'LIE',
                'iso' => 'LI',
                'name' => 'Liechtenstein',
                'numcode' => 438,
                'flag' => 'Liechtenshein-Flag.png',
            ],
            'LT' => [
                'id' => 'LTU',
                'iso' => 'LT',
                'name' => 'Lithuania',
                'numcode' => 440,
                'flag' => 'Lithuania-Flag.png',
            ],
            'LU' => [
                'id' => 'LUX',
                'iso' => 'LU',
                'name' => 'Luxembourg',
                'numcode' => 442,
                'flag' => 'Luxembourg-Flag.png',
            ],
            'MO' => [
                'id' => 'MAC',
                'iso' => 'MO',
                'name' => 'Macao',
                'numcode' => 446,
                'flag' => 'Macau-Flag.png',
            ],
            'MK' => [
                'id' => 'MKD',
                'iso' => 'MK',
                'name' => 'Macedonia, the Former Yugoslav Republic of',
                'numcode' => 807,
                'flag' => 'Macedonia-Flag.png',
            ],
            'MG' => [
                'id' => 'MDG',
                'iso' => 'MG',
                'name' => 'Madagascar',
                'numcode' => 450,
                'flag' => 'Madagascar-Flag.png',
            ],
            'MW' => [
                'id' => 'MWI',
                'iso' => 'MW',
                'name' => 'Malawi',
                'numcode' => 454,
                'flag' => 'Malawi-Flag.png',
            ],
            'MY' => [
                'id' => 'MYS',
                'iso' => 'MY',
                'name' => 'Malaysia',
                'numcode' => 458,
                'flag' => 'Malaysia-Flag.png',
            ],
            'MV' => [
                'id' => 'MDV',
                'iso' => 'MV',
                'name' => 'Maldives',
                'numcode' => 462,
                'flag' => 'Maldives-Flag.png',
            ],
            'ML' => [
                'id' => 'MLI',
                'iso' => 'ML',
                'name' => 'Mali',
                'numcode' => 466,
                'flag' => 'Mali-Flag.png',
            ],
            'MT' => [
                'id' => 'MLT',
                'iso' => 'MT',
                'name' => 'Malta',
                'numcode' => 470,
                'flag' => 'Malta-Flag.png',
            ],
            'MH' => [
                'id' => 'MHL',
                'iso' => 'MH',
                'name' => 'Marshall Islands',
                'numcode' => 584,
                'flag' => 'Marshall-Islands-Flag.png',
            ],
            'MQ' => [
                'id' => 'MTQ',
                'iso' => 'MQ',
                'name' => 'Martinique',
                'numcode' => 474,
                'flag' => 'France-Flag.png',
            ],
            'MR' => [
                'id' => 'MRT',
                'iso' => 'MR',
                'name' => 'Mauritania',
                'numcode' => 478,
                'flag' => 'Mauritania-Flag.png',
            ],
            'MU' => [
                'id' => 'MUS',
                'iso' => 'MU',
                'name' => 'Mauritius',
                'numcode' => 480,
                'flag' => 'Mauritius-Flag.png',
            ],
            'YT' => [
                'id' => 'YT',
                'iso' => 'YT',
                'name' => 'Mayotte',
                'numcode' => 0,
                'flag' => 'France-Flag.png',
            ],
            'MX' => [
                'id' => 'MEX',
                'iso' => 'MX',
                'name' => 'Mexico',
                'numcode' => 484,
                'flag' => 'Mexico-Flag.png',
            ],
            'FM' => [
                'id' => 'FSM',
                'iso' => 'FM',
                'name' => 'Micronesia, Federated States of',
                'numcode' => 583,
                'flag' => 'Micronesia-Flag.png',
            ],
            'MD' => [
                'id' => 'MDA',
                'iso' => 'MD',
                'name' => 'Moldova, Republic of',
                'numcode' => 498,
                'flag' => 'Moldova-Flag.png',
            ],
            'MC' => [
                'id' => 'MCO',
                'iso' => 'MC',
                'name' => 'Monaco',
                'numcode' => 492,
                'flag' => 'Monaco-Flag.png',
            ],
            'MN' => [
                'id' => 'MNG',
                'iso' => 'MN',
                'name' => 'Mongolia',
                'numcode' => 496,
                'flag' => 'Mongolia-Flag.png',
            ],
            'MS' => [
                'id' => 'MSR',
                'iso' => 'MS',
                'name' => 'Montserrat',
                'numcode' => 500,
                'flag' => 'Montserrat-Flag.png',
            ],
            'MA' => [
                'id' => 'MAR',
                'iso' => 'MA',
                'name' => 'Morocco',
                'numcode' => 504,
                'flag' => 'Morocco-Flag.png',
            ],
            'MZ' => [
                'id' => 'MOZ',
                'iso' => 'MZ',
                'name' => 'Mozambique',
                'numcode' => 508,
                'flag' => 'Mozambique-Flag.png',
            ],
            'MM' => [
                'id' => 'MMR',
                'iso' => 'MM',
                'name' => 'Myanmar',
                'numcode' => 104,
                'flag' => 'Myanmar-Flag.png',
            ],
            'NA' => [
                'id' => 'NAM',
                'iso' => 'NA',
                'name' => 'Namibia',
                'numcode' => 516,
                'flag' => 'Namibia-Flag.png',
            ],
            'NR' => [
                'id' => 'NRU',
                'iso' => 'NR',
                'name' => 'Nauru',
                'numcode' => 520,
                'flag' => 'Nauru-Flag.png',
            ],
            'NP' => [
                'id' => 'NPL',
                'iso' => 'NP',
                'name' => 'Nepal',
                'numcode' => 524,
                'flag' => 'Nepal-Flag.png',
            ],
            'NL' => [
                'id' => 'NLD',
                'iso' => 'NL',
                'name' => 'Netherlands',
                'numcode' => 528,
                'flag' => 'Netherlands-Flag.png',
            ],
            'AN' => [
                'id' => 'ANT',
                'iso' => 'AN',
                'name' => 'Netherlands Antilles',
                'numcode' => 530,
                'flag' => 'Netherlands-Antilles-Flag.png',
            ],
            'NC' => [
                'id' => 'NCL',
                'iso' => 'NC',
                'name' => 'New Caledonia',
                'numcode' => 540,
                'flag' => 'France-Flag.png',
            ],
            'NZ' => [
                'id' => 'NZL',
                'iso' => 'NZ',
                'name' => 'New Zealand',
                'numcode' => 554,
                'flag' => 'New-Zealand-Flag.png',
            ],
            'NI' => [
                'id' => 'NIC',
                'iso' => 'NI',
                'name' => 'Nicaragua',
                'numcode' => 558,
                'flag' => 'Nicaragua-Flag.png',
            ],
            'NE' => [
                'id' => 'NER',
                'iso' => 'NE',
                'name' => 'Niger',
                'numcode' => 562,
                'flag' => 'Niger-Flag.png',
            ],
            'NG' => [
                'id' => 'NGA',
                'iso' => 'NG',
                'name' => 'Nigeria',
                'numcode' => 566,
                'flag' => 'Nigeria-Flag.png',
            ],
            'NU' => [
                'id' => 'NIU',
                'iso' => 'NU',
                'name' => 'Niue',
                'numcode' => 570,
                'flag' => 'United-Kingdom-Flag.png',
            ],
            'NF' => [
                'id' => 'NFK',
                'iso' => 'NF',
                'name' => 'Norfolk Island',
                'numcode' => 574,
                'flag' => 'Australia-Flag.png',
            ],
            'MP' => [
                'id' => 'MNP',
                'iso' => 'MP',
                'name' => 'Northern Mariana Islands',
                'numcode' => 580,
                'flag' => 'United-States-of-America-Flag.png',
            ],
            'NO' => [
                'id' => 'NOR',
                'iso' => 'NO',
                'name' => 'Norway',
                'numcode' => 578,
                'flag' => 'Norway-Flag.png',
            ],
            'OM' => [
                'id' => 'OMN',
                'iso' => 'OM',
                'name' => 'Oman',
                'numcode' => 512,
                'flag' => 'Oman-Flag.png',
            ],
            'PK' => [
                'id' => 'PAK',
                'iso' => 'PK',
                'name' => 'Pakistan',
                'numcode' => 586,
                'flag' => 'Pakistan-Flag.png',
            ],
            'PW' => [
                'id' => 'PLW',
                'iso' => 'PW',
                'name' => 'Palau',
                'numcode' => 585,
                'flag' => 'Palau-Flag.png',
            ],
            'PS' => [
                'id' => 'PS',
                'iso' => 'PS',
                'name' => 'Palestinian Territory, Occupied',
                'numcode' => 0,
                'flag' => 'Palestine-Flag.png',
            ],
            'PA' => [
                'id' => 'PAN',
                'iso' => 'PA',
                'name' => 'Panama',
                'numcode' => 591,
                'flag' => 'Panama-Flag.png',
            ],
            'PG' => [
                'id' => 'PNG',
                'iso' => 'PG',
                'name' => 'Papua New Guinea',
                'numcode' => 598,
                'flag' => 'Papua-New-Guinea-Flag.png',
            ],
            'PY' => [
                'id' => 'PRY',
                'iso' => 'PY',
                'name' => 'Paraguay',
                'numcode' => 600,
                'flag' => 'Paraguay-Flag.png',
            ],
            'PE' => [
                'id' => 'PER',
                'iso' => 'PE',
                'name' => 'Peru',
                'numcode' => 604,
                'flag' => 'Peru-Flag.png',
            ],
            'PH' => [
                'id' => 'PHL',
                'iso' => 'PH',
                'name' => 'Philippines',
                'numcode' => 608,
                'flag' => 'Philippines-Flag.png',
            ],
            'PN' => [
                'id' => 'PCN',
                'iso' => 'PN',
                'name' => 'Pitcairn',
                'numcode' => 612,
                'flag' => 'United-Kingdom-Flag.png',
            ],
            'PL' => [
                'id' => 'POL',
                'iso' => 'PL',
                'name' => 'Poland',
                'numcode' => 616,
                'flag' => 'Poland-Flag.png',
            ],
            'PT' => [
                'id' => 'PRT',
                'iso' => 'PT',
                'name' => 'Portugal',
                'numcode' => 620,
                'flag' => 'Portugal-Flag.png',
            ],
            'PR' => [
                'id' => 'PRI',
                'iso' => 'PR',
                'name' => 'Puerto Rico',
                'numcode' => 630,
                'flag' => 'Puerto-Rico-Flag.png',
            ],
            'QA' => [
                'id' => 'QAT',
                'iso' => 'QA',
                'name' => 'Qatar',
                'numcode' => 634,
                'flag' => 'Qatar-Flag.png',
            ],
            'RE' => [
                'id' => 'REU',
                'iso' => 'RE',
                'name' => 'Reunion',
                'numcode' => 638,
                'flag' => 'France-Flag.png',
            ],
            'RO' => [
                'id' => 'ROM',
                'iso' => 'RO',
                'name' => 'Romania',
                'numcode' => 642,
                'flag' => 'Romania-Flag.png',
            ],
            'RU' => [
                'id' => 'RUS',
                'iso' => 'RU',
                'name' => 'Russian Federation',
                'numcode' => 643,
                'flag' => 'Russian-Federation-Flag.png',
            ],
            'RW' => [
                'id' => 'RWA',
                'iso' => 'RW',
                'name' => 'Rwanda',
                'numcode' => 646,
                'flag' => 'Rwanda-Flag.png',
            ],
            'SH' => [
                'id' => 'SHN',
                'iso' => 'SH',
                'name' => 'Saint Helena',
                'numcode' => 654,
                'flag' => 'United-Kingdom-Flag.png',
            ],
            'KN' => [
                'id' => 'KNA',
                'iso' => 'KN',
                'name' => 'Saint Kitts and Nevis',
                'numcode' => 659,
                'flag' => 'St-Kitts-and-Nevis-Flag.png',
            ],
            'LC' => [
                'id' => 'LCA',
                'iso' => 'LC',
                'name' => 'Saint Lucia',
                'numcode' => 662,
                'flag' => 'Saint-Lucia-Flag.png',
            ],
            'PM' => [
                'id' => 'SPM',
                'iso' => 'PM',
                'name' => 'Saint Pierre and Miquelon',
                'numcode' => 666,
                'flag' => 'France-Flag.png',
            ],
            'VC' => [
                'id' => 'VCT',
                'iso' => 'VC',
                'name' => 'Saint Vincent and the Grenadines',
                'numcode' => 670,
                'flag' => 'St-Vincent-and-the-Grenadines-Flag.png',
            ],
            'WS' => [
                'id' => 'WSM',
                'iso' => 'WS',
                'name' => 'Samoa',
                'numcode' => 882,
                'flag' => 'Samoa-Flag.png',
            ],
            'SM' => [
                'id' => 'SMR',
                'iso' => 'SM',
                'name' => 'San Marino',
                'numcode' => 674,
                'flag' => 'San-Marino-Flag.png',
            ],
            'ST' => [
                'id' => 'STP',
                'iso' => 'ST',
                'name' => 'Sao Tome and Principe',
                'numcode' => 678,
                'flag' => 'Sao-Tome-and-Principe-Flag.png',
            ],
            'SA' => [
                'id' => 'SAU',
                'iso' => 'SA',
                'name' => 'Saudi Arabia',
                'numcode' => 682,
                'flag' => 'Saudi-Arabia-Flag.png',
            ],
            'SN' => [
                'id' => 'SEN',
                'iso' => 'SN',
                'name' => 'Senegal',
                'numcode' => 686,
                'flag' => 'Senegal-Flag.png',
            ],
            'CS' => [
                'id' => 'CS',
                'iso' => 'CS',
                'name' => 'Serbia and Montenegro',
                'numcode' => 0,
                'flag' => 'Serbia-Flag.png',
            ],
            'SC' => [
                'id' => 'SYC',
                'iso' => 'SC',
                'name' => 'Seychelles',
                'numcode' => 690,
                'flag' => 'Seychelles-Flag.png',
            ],
            'SL' => [
                'id' => 'SLE',
                'iso' => 'SL',
                'name' => 'Sierra Leone',
                'numcode' => 694,
                'flag' => 'Sierra-Leone-Flag.png',
            ],
            'SG' => [
                'id' => 'SGP',
                'iso' => 'SG',
                'name' => 'Singapore',
                'numcode' => 702,
                'flag' => 'Singapore-Flag.png',
            ],
            'SK' => [
                'id' => 'SVK',
                'iso' => 'SK',
                'name' => 'Slovakia',
                'numcode' => 703,
                'flag' => 'Slovakia-Flag.png',
            ],
            'SI' => [
                'id' => 'SVN',
                'iso' => 'SI',
                'name' => 'Slovenia',
                'numcode' => 705,
                'flag' => 'Slovenia-Flag.png',
            ],
            'SB' => [
                'id' => 'SLB',
                'iso' => 'SB',
                'name' => 'Solomon Islands',
                'numcode' => 90,
                'flag' => 'Solomon-Islands-Flag.png',
            ],
            'SO' => [
                'id' => 'SOM',
                'iso' => 'SO',
                'name' => 'Somalia',
                'numcode' => 706,
                'flag' => 'Somalia-Flag.png',
            ],
            'ZA' => [
                'id' => 'ZAF',
                'iso' => 'ZA',
                'name' => 'South Africa',
                'numcode' => 710,
                'flag' => 'South-Africa-Flag.png',
            ],
            'GS' => [
                'id' => 'GS',
                'iso' => 'GS',
                'name' => 'South Georgia and the South Sandwich Islands',
                'numcode' => 0,
                'flag' => 'South-Korea-Flag.png',
            ],
            'ES' => [
                'id' => 'ESP',
                'iso' => 'ES',
                'name' => 'Spain',
                'numcode' => 724,
                'flag' => 'Spain-Flag.png',
            ],
            'LK' => [
                'id' => 'LKA',
                'iso' => 'LK',
                'name' => 'Sri Lanka',
                'numcode' => 144,
                'flag' => 'Sri-Lanka-Flag.png',
            ],
            'SD' => [
                'id' => 'SDN',
                'iso' => 'SD',
                'name' => 'Sudan',
                'numcode' => 736,
                'flag' => 'Sudan-Flag.png',
            ],
            'SR' => [
                'id' => 'SUR',
                'iso' => 'SR',
                'name' => 'Suriname',
                'numcode' => 740,
                'flag' => 'Suriname-Flag.png',
            ],
            'SJ' => [
                'id' => 'SJM',
                'iso' => 'SJ',
                'name' => 'Svalbard and Jan Mayen',
                'numcode' => 744,
                'flag' => 'Norway-Flag.png',
            ],
            'SZ' => [
                'id' => 'SWZ',
                'iso' => 'SZ',
                'name' => 'Swaziland',
                'numcode' => 748,
                'flag' => 'Swaziland-Flag.png',
            ],
            'SE' => [
                'id' => 'SWE',
                'iso' => 'SE',
                'name' => 'Sweden',
                'numcode' => 752,
                'flag' => 'Sweden-Flag.png',
            ],
            'CH' => [
                'id' => 'CHE',
                'iso' => 'CH',
                'name' => 'Switzerland',
                'numcode' => 756,
                'flag' => 'Switzerland-Flag.png',
            ],
            'SY' => [
                'id' => 'SYR',
                'iso' => 'SY',
                'name' => 'Syrian Arab Republic',
                'numcode' => 760,
                'flag' => 'Syria-Flag.png',
            ],
            'TW' => [
                'id' => 'TWN',
                'iso' => 'TW',
                'name' => 'Taiwan, Province of China',
                'numcode' => 158,
                'flag' => 'Taiwan-Flag.png',
            ],
            'TJ' => [
                'id' => 'TJK',
                'iso' => 'TJ',
                'name' => 'Tajikistan',
                'numcode' => 762,
                'flag' => 'Tajikistan-Flag.png',
            ],
            'TZ' => [
                'id' => 'TZA',
                'iso' => 'TZ',
                'name' => 'Tanzania, United Republic of',
                'numcode' => 834,
                'flag' => 'Tanzania-Flag.png',
            ],
            'TH' => [
                'id' => 'THA',
                'iso' => 'TH',
                'name' => 'Thailand',
                'numcode' => 764,
                'flag' => 'Thailand-Flag.png',
            ],
            'TL' => [
                'id' => 'TL',
                'iso' => 'TL',
                'name' => 'Timor-Leste',
                'numcode' => 0,
                'flag' => 'Timor-Leste-Flag.png',
            ],
            'TG' => [
                'id' => 'TGO',
                'iso' => 'TG',
                'name' => 'Togo',
                'numcode' => 768,
                'flag' => 'Togo-Flag.png',
            ],
            'TK' => [
                'id' => 'TKL',
                'iso' => 'TK',
                'name' => 'Tokelau',
                'numcode' => 772,
                'flag' => 'New-Zealand-Flag.png',
            ],
            'TO' => [
                'id' => 'TON',
                'iso' => 'TO',
                'name' => 'Tonga',
                'numcode' => 776,
                'flag' => 'Tonga-Flag.png',
            ],
            'TT' => [
                'id' => 'TTO',
                'iso' => 'TT',
                'name' => 'Trinidad and Tobago',
                'numcode' => 780,
                'flag' => 'Trinidad-and-Tobago-Flag.png',
            ],
            'TN' => [
                'id' => 'TUN',
                'iso' => 'TN',
                'name' => 'Tunisia',
                'numcode' => 788,
                'flag' => 'Tunisia-Flag.png',
            ],
            'TR' => [
                'id' => 'TUR',
                'iso' => 'TR',
                'name' => 'Turkey',
                'numcode' => 792,
                'flag' => 'Turkey-Flag.png',
            ],
            'TM' => [
                'id' => 'TKM',
                'iso' => 'TM',
                'name' => 'Turkmenistan',
                'numcode' => 795,
                'flag' => 'Turkmenistan-Flag.png',
            ],
            'TC' => [
                'id' => 'TCA',
                'iso' => 'TC',
                'name' => 'Turks and Caicos Islands',
                'numcode' => 796,
                'flag' => 'Turks-and-Caicos-Islands-Flag.png',
            ],
            'TV' => [
                'id' => 'TUV',
                'iso' => 'TV',
                'name' => 'Tuvalu',
                'numcode' => 798,
                'flag' => 'Tuvalu-Flag.png',
            ],
            'UG' => [
                'id' => 'UGA',
                'iso' => 'UG',
                'name' => 'Uganda',
                'numcode' => 800,
                'flag' => 'Uganda-Flag.png',
            ],
            'UA' => [
                'id' => 'UKR',
                'iso' => 'UA',
                'name' => 'Ukraine',
                'numcode' => 804,
                'flag' => 'Ukraine-Flag.png',
            ],
            'AE' => [
                'id' => 'ARE',
                'iso' => 'AE',
                'name' => 'United Arab Emirates',
                'numcode' => 784,
                'flag' => 'United-Arab-Emirates-Flag.png',
            ],
            'GB' => [
                'id' => 'GBR',
                'iso' => 'GB',
                'name' => 'United Kingdom',
                'numcode' => 826,
                'flag' => 'United-Kingdom-Flag.png',
            ],
            'US' => [
                'id' => 'USA',
                'iso' => 'US',
                'name' => 'United States',
                'numcode' => 840,
                'flag' => 'United-States-of-America-Flag.png',
            ],
            'UM' => [
                'id' => 'UM',
                'iso' => 'UM',
                'name' => 'United States Minor Outlying Islands',
                'numcode' => 0,
                'flag' => 'United-States-of-America-Flag.png',
            ],
            'UY' => [
                'id' => 'URY',
                'iso' => 'UY',
                'name' => 'Uruguay',
                'numcode' => 858,
                'flag' => 'Uruguay-Flag.png',
            ],
            'UZ' => [
                'id' => 'UZB',
                'iso' => 'UZ',
                'name' => 'Uzbekistan',
                'numcode' => 860,
                'flag' => 'Uzbekistan-Flag.png',
            ],
            'VU' => [
                'id' => 'VUT',
                'iso' => 'VU',
                'name' => 'Vanuatu',
                'numcode' => 548,
                'flag' => 'Vanutau-Flag.png',
            ],
            'VE' => [
                'id' => 'VEN',
                'iso' => 'VE',
                'name' => 'Venezuela',
                'numcode' => 862,
                'flag' => 'Venezuela-Flag.png',
            ],
            'VN' => [
                'id' => 'VNM',
                'iso' => 'VN',
                'name' => 'Viet Nam',
                'numcode' => 704,
                'flag' => 'Viet-Nam-Flag.png',
            ],
            'VG' => [
                'id' => 'VGB',
                'iso' => 'VG',
                'name' => 'Virgin Islands, British',
                'numcode' => 92,
                'flag' => 'Virgin-Islands-British-Flag.png',
            ],
            'VI' => [
                'id' => 'VIR',
                'iso' => 'VI',
                'name' => 'Virgin Islands, U.s.',
                'numcode' => 850,
                'flag' => 'Virgin-Islands-US-Flag.png',
            ],
            'WF' => [
                'id' => 'WLF',
                'iso' => 'WF',
                'name' => 'Wallis and Futuna',
                'numcode' => 876,
                'flag' => 'France-Flag.png',
            ],
            'EH' => [
                'id' => 'ESH',
                'iso' => 'EH',
                'name' => 'Western Sahara',
                'numcode' => 732,
                'flag' => 'Western-Sahara-Flag.png',
            ],
            'YE' => [
                'id' => 'YEM',
                'iso' => 'YE',
                'name' => 'Yemen',
                'numcode' => 887,
                'flag' => 'Yemen-Flag.png',
            ],
            'ZM' => [
                'id' => 'ZMB',
                'iso' => 'ZM',
                'name' => 'Zambia',
                'numcode' => 894,
                'flag' => 'Zambia-Flag.png',
            ],
            'ZW' => [
                'id' => 'ZWE',
                'iso' => 'ZW',
                'name' => 'Zimbabwe',
                'numcode' => 716,
                'flag' => 'Zimbabwe-Flag.png',
            ],
        ];
    }

    public function getCountries(): array
    {
        return $this->countries;
    }
}
